version: 2
jobs:
  build:
    docker: 
      - image: node:7.4.0
    working_directory: ~/repo
    steps:

      - checkout

      # new remote environment is created, and the primary container is configured to use it.
      - setup_remote_docker

       # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      #- run: npm test

      # build the application
      #- run: npm run build

      # install docker client
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: ls ~/repo

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t danielesalvatore/e2e-testing-playground-server:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push danielesalvatore/e2e-testing-playground-server:$TAG
          docker push danielesalvatore/e2e-testing-playground-server
